### ISSUE TITLE
Feature Req: on/off button for auto-reload js

### ISSUE THREAD

**Issue by lainchan** [lainchan/lainchan#1]
title

**Comment by tjohnman** [comment]
I don't quite understand (because turning auto-reload on and off is a feature that's already implemented).

**Comment by haspagan** [comment]
I would like you to elaborate on this too, as it's not that clear to understand : Are you talking about a global auto-refresh toggle option, like something similar to the picture?

![lain_auto](https://cloud.githubusercontent.com/assets/10586042/10123920/bc38e8b2-6546-11e5-9f8a-1662a3c327d5.jpg)

**Comment by rajlaksh** [comment]
Maybe Question is related to [Auto seconds] function.

**Comment by Appleman1234** [comment]
Implemented, closing.
