### ISSUE TITLE
OK if I point lain.space to lainchan servers?

### ISSUE THREAD

**Issue by WillemMali** [lainchan/lainchan#105]
Hi,

I'm not a LainChan user, but I'm a Lain fan. I currently own the domain `lain.space`, but I don't have time to do much with it now.

Is it OK if I point it to the LainChan servers? I don't like my domain names catching dust. You'd retain the option to not serve requests to visitors to `lain.space` because the `host` header is different, unlike the case where I'd set up a webserver with a 302 redirect.

Have a nice day,
Willem

**Comment by Appleman1234** [comment]
I don't mind, however I am not sure how that would work with the current content security policy, and also regarding SSL.

**Comment by WillemMali** [comment]
My A record is now pointing to `107.161.19.243`, the IP address of
Lainchan. Lainchan redirects `107.161.19.243` to `https://www.lainchan.org/`,
so I'm guessing this will work.

I don't think it'd be super secure re: relying on plain HTTP redirects, but
if that matters and Lainchan is using Let's Encrypt it shouldn't be too
hard to add a cert for `lain.space`.

It should take about 4 hours for the DNS records to reach your DNS server.

**Comment by Appleman1234** [comment]
This is completed, closing. reopen if necessary.
