### ISSUE TITLE
Image resize failure

### ISSUE THREAD

**Issue by barrucadu** [lainchan/lainchan#111]
Tried to post the attached image, got this error:

> Failed to resize image! Details: gm convert: zTXt: CRC error (/tmp/phpAGJTrL).

![personalfinance_uk](https://user-images.githubusercontent.com/75235/27201427-8e25d058-5215-11e7-8de4-1f789d8c2c19.png)

**Comment by barrucadu** [comment]
In case uploading to github altered the image in any way, it's the spreadsheet on /r/UKPersonalFinance: https://i.imgur.com/ezGWhE3.png

**Comment by Appleman1234** [comment]
Closing ticket as per image below, the image in question is invalid with regards to PNG specification.
![image](https://user-images.githubusercontent.com/13495053/52540645-87bc6480-2dd7-11e9-8f6e-051cb2dd9427.png)
