### ISSUE TITLE
Another error from editing the config..

### ISSUE THREAD

**Issue by ljayvee** [lainchan/lainchan#135]
Error recursion detected with Caught fatal error: Uncaught Twig_Error_Loader: The "" directory does not exist. in /var/www/html/lainchan/inc/lib/Twig/Loader/Filesystem.php:93 Stack trace: #0 /var/www/html/lainchan/inc/lib/Twig/Loader/Filesystem.php(75): Twig_Loader_Filesystem->addPath(NULL, '__main__') #1 /var/www/html/lainchan/inc/template.php(23): Twig_Loader_Filesystem->setPaths(Array) #2 /var/www/html/lainchan/inc/template.php(38): load_twig() #3 /var/www/html/lainchan/inc/error.php(88): Element('error.html', Array) #4 /var/www/html/lainchan/inc/error.php(12): error('syntax error, u...') #5 [internal function]: exception_handler(Object(ParseError)) #6 {main} thrown in /var/www/html/lainchan/inc/lib/Twig/Loader/Filesystem.php at line 93
Original error:syntax error, unexpected '$config' (T_VARIABLE)

**Comment by Appleman1234** [comment]
I need more information in order to help resolve the  to problem, feel free to provide it here or contact me on the IRC. The error message you have provided here is incomplete.

**Comment by ljayvee** [comment]
Which IRC can i reach you on? lainchan.org/irc?
