### ISSUE TITLE
Install.php permissions

### ISSUE THREAD

**Issue by c0mp1e-x** [lainchan/lainchan#137]
I'm having an issue while trying to install Lainchan. When I go to http://MY_IP/install.php I get this error

"install.php does not have permission to write to /inc/, without permission the installer cannot continue"
I've tried giving install.php permissions but I'm getting the same message, I'm also not even able to find a /inc/ directory so I'm not sure how to proceed with installation.
 
EDIT: Suddenly /inc/ has appeared in my HTML directory, and its filled with stuff as well, however I'm still getting the error from install.php about permissions

**Comment by c0mp1e-x** [comment]
Suddenly /inc/ has appeared in my HTML directory, and its filled with stuff as well, however I'm still getting the error from install.php about permissions

**Comment by fuerbringer** [comment]
It sounds like the files you extracted to your webroot don't have the correct user permissions. They should be owned by the webserver user. Find out what user your webserver runs under and run something like this (with care): `chown <user>:<user> -R /path/to/chan/webroot`

The user is `www-data` in most cases. Don't run `chmod 777`.

**Comment by c0mp1e-x** [comment]
@fuerbringer That seems to have given it the correct permissions but I am now getting this error when I try and navigate to install.php

"Error recursion detected with Caught fatal error: Uncaught Twig_Error_Loader: The "" directory does not exist. in /var/www/html/lainchan/inc/lib/Twig/Loader/Filesystem.php:93 Stack trace: #0 /var/www/html/lainchan/inc/lib/Twig/Loader/Filesystem.php(75): Twig_Loader_Filesystem->addPath(NULL, '__main__') #1 /var/www/html/lainchan/inc/template.php(23): Twig_Loader_Filesystem->setPaths(Array) #2 /var/www/html/lainchan/inc/template.php(38): load_twig() #3 /var/www/html/lainchan/inc/error.php(88): Element('error.html', Array) #4 /var/www/html/lainchan/inc/error.php(12): error('Call to undefin...') #5 [internal function]: exception_handler(Object(Error)) #6 {main} thrown in /var/www/html/lainchan/inc/lib/Twig/Loader/Filesystem.php at line 93
Original error:Call to undefined function mb_internal_encoding()"

**Comment by c0mp1e-x** [comment]
I just realized that its probably an error with mbstring because this is a fresh install of LAMP and I forgot to install it.
