### ISSUE TITLE
How to set add custom stylesheets

### ISSUE THREAD

**Issue by crimeangothic** [lainchan/lainchan#139]
I uncommented the dark theme in config.php and it didn't come up in the footer, is there something else i'm meant to do? Should i put it in instance_config?

**Comment by crimeangothic** [comment]
Also, how would i add a dropdown box that lets people select themes? @Appleman1234

**Comment by Appleman1234** [comment]
For each stylesheet you need to add $config['stylesheets']['stylesheetnamehere'] = 'nameofcssfile.css'; to instance-config.php. 
For the dropdown box that lets people choose themes you need to add $config['additional_javascript'][] = 'js/style-select.js'; to instance-config.php.

**Comment by crimeangothic** [comment]
didnt' work
