### ISSUE TITLE
Bans are impossible under PHP 7.1

### ISSUE THREAD

**Issue by ghost** [lainchan/lainchan#141]
Upon clicking the [b] (Ban) button from the moderator interface, the following error will be thrown: 
`Undefined index: thread in /documentroot/lainchan/inc/mod/pages.php at line 1843`
Following generic advice, I wrapped it up in `isset`, like so:
```
if(isset($_GET['thread'])) {
        $args['thread'] = $_GET['thread'];
    }
```

The ban form will now generate successfully.

On my (local machine), this seems to fix the problem. The PHP version running on my local machine is: `PHP 7.0.22-0ubuntu0.16.04.1`. Everything works as expected, and members of staff can place timed bans.

However, on my server, I run into another error. This error is thrown whenever a member of staff tries to place a non-permanent ban: `A non-numeric value encountered in /documentroot/inc/bans.php at line 50`

On my server, I am running PHP 7.1.13-1. It seems that new behavior was introduced in this version, causing the error: https://stackoverflow.com/questions/42044127/warning-a-non-numeric-value-encountered

**Comment by Appleman1234** [comment]
Fixed as per https://github.com/lainchan/lainchan/commit/dce8a6e1ec82b876d217418672f16e5765f66c43
