### ISSUE TITLE
Videos opening in new tab

### ISSUE THREAD

**Issue by crimeangothic** [lainchan/lainchan#143]
What module/js do I need to enable so when I click on a video a player comes up in the thread rather than opening the file in a new tab

**Comment by Appleman1234** [comment]
You need either the first or second one, and then the third one.
$config['additional_javascript'][] = 'js/options.js'
$config['additional_javascript'][] = 'js/webm-settings.js'
$config['additional_javascript'][] = 'js/expand-video.js'
