### ISSUE TITLE
Allow CORS

### ISSUE THREAD

**Issue by chudeki8** [lainchan/lainchan#15]
Hi, I saw that CORS don't work for ajax javascript stuff. This would be pretty great to add for external tools (I can help write mobile/desktop/whatever programs for lainchan but they need XHR to interact). 

The only thing to do is add something like this to your nginx config:

```
location / {  # or whatever actual location
  add_header Access-Control-Allow-Origin *;
}
```

**Comment by darkengine-io** [comment]
Here's what lainchan security head ncl had to say:

> whitelisting is better than blacklisting, if someone is developing extra
scripts or whatever for lainchan then only allow what's needed for those
to work (if that's not too much hassle)

So, what exactly is it that's being developed, and what does it need to request?

**Comment by chudeki8** [comment]
So... the idea was to use future library № 5 to build hybrid apps for mobile and desktop apps for linux, windoze, and osx using one lisp code base. I've gotten kind of busy though so I probly wouldn't be able to work on it for the next month or two. It sounds like a lot but it should only take about a week or two.

The app would make XHR requests to lainchan to get json pages (catalog.json, page.json, thread-list.json, and thread.json for all the boards). Do you have suggestions for how to restrict the CORS? It seems like since all the XHR's would be clientside, there would be a bunch of random IP addresses making the requests.

**Comment by barrucadu** [comment]
@chudeki8, could you give a concrete example where this would be useful? Is the idea that some app would have a javascript component running in the browser talking to some remote service, and so need this to be able to achieve that communication?

**Comment by chudeki8** [comment]
The plan is to write the app in clojurescript which compiles to javascript. It's built on a framework that can publish apps to cordova/phonegap for mobile and nw.js (node-webkit) for desktop.

It would pull the json from lainchan and do databinding to render the content as a page in the app. For that it needs lainchan to submit the access-control header on responses, otherwise any xhrs will throw an error. Maybe it would make sense to limit the `access-control-allow-methods` to `get` only for now. That would allow the app to pull json for showing the site content. If it ever gets to creating posts or deleting/reporting posts, maybe lainchan could use an access token for authentication? Any ideas?

Sorry btw that it's kinda been in limbo. I could try picking it up again and maybe post the repo. There are some cool ideas like using applicative functors for fetching/posting json, functional lenses, and some other stuff.
