### ISSUE TITLE
No 'News' Module?

### ISSUE THREAD

**Issue by Crakila** [lainchan/lainchan#151]
I installed the 'Basic' theme to implement news on the site, but there is nothing in `/mod.php` that shows where to create news posts.

This tinyboard comment suggests that it's under the "Messages" category...which I am aware that lainchan doesn't have. https://github.com/savetheinternet/Tinyboard/issues/137#issuecomment-22828875

Any help would be appreciated :)

**Comment by Appleman1234** [comment]
It was removed from the menu as part of a simplification. It can still be used adding edit_news after domain.org/mod.php?/
