### ISSUE TITLE
Database error 

### ISSUE THREAD

**Issue by klorophatu** [lainchan/lainchan#155]
```
Database error: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)
```
This is what I get
When I'm using vichan it works fine

**Comment by rmrhz** [comment]
Not an eror related to lainchan

**Comment by klorophatu** [comment]
What is it related to then? It works perfectly fine on vichan but when I use lainchan it gives me this error every time, am I supposed to open this issue on mysql's page or what?
It also works perfectly fine on any other program that uses mysql

**Comment by Appleman1234** [comment]
rmrhz is correct that this doesn't seem like an error specific to lainchan, however I am happy to help you troubleshoot it.

Based on the error message it looks like you haven't setup the config['db'] variables correcly in [inc/config.php](https://github.com/lainchan/lainchan/blob/master/inc/config.php#L92) or the file you need to create to customize your instance configuration which is inc/instance-config.php. Specifically the password variable mentioned in the link above.

If that doesn't work, then please ensure you have a created a relevant MySQL user for lainchan to use as per [Digital Ocean MySQL user creation tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-new-user-and-grant-permissions-in-mysql).

Are you using install.php ? There are some upstream changes we don't have merged from vichan, that we could merge for that file, but non of them seem related to the error message you provided, if you provide more information about what steps you tried, then it would be easier to troubleshoot your issue. For other advice see [the following StackOverflow post and answers](https://stackoverflow.com/questions/31154124/sqlstatehy000-1045-access-denied-for-user-usernamelocalhost-using-cakep)

**Comment by klorophatu** [comment]
What I did was git clone the current master branch of lainchan into the root of my website, I then chown'd it to www-data. I added the mysql user, database and password and then clicked complete installation, after that it gave me that error

**Comment by Appleman1234** [comment]
Added the user to where ? To mysql ? to the instance-config.php ?

**Comment by klorophatu** [comment]
I added them to the input boxes during the install.php process

**Comment by Appleman1234** [comment]
Was the instance-config.php generated correctly with the values you added ? Because that error message has a blank username and a blank password ?

**Comment by Appleman1234** [comment]
You have to create the database and mysql user using 
`CREATE DATABASE <databasename>;
CREATE USER 'username'@'hostname' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON <databasename>.* TO 'username'@'hostname';
FLUSH PRIVELEGES;` where databasename is the database in instance-config.php  username is the user , and hostname is the server and password is the password.

**Comment by klorophatu** [comment]
OK, I think I fixed it somehow
What I did was, go through the installation process, once that error popped up, I opened up mysql and added the privileges to it and then flushed them, that somehow made it work

**Comment by klorophatu** [comment]
Also, I just got another error
```
count(): Parameter must be an array or an object that implements Countable in /home/website/lainchan/templates/cache/3d/3d62c6ffca72a594e8ba532c526999cf08dde7820eddfa7b55bfe8cc0acc8177.php at line 95
```

**Comment by Appleman1234** [comment]
Run a git pull to get the latest update which should resolve the issue as per https://github.com/lainchan/lainchan/issues/156 .
