### ISSUE TITLE
Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by gegtor** [lainchan/lainchan#156]
Same thing as here #93 

Ubuntu 18.04
Latest MySQL

**Comment by gegtor** [comment]
I continued with installation and I'm getting

`
count(): Parameter must be an array or an object that implements Countable in /var/www/xxx.org/templates/cache/b9/b902dc51ef56b43254c79b6ee347a2bdf43a5aed4d993e04cc7c135ef03efe0b.php at line 220
`

**Comment by lunarthegrey** [comment]
Same issue here.

**Comment by Appleman1234** [comment]
This should be fixed by the latest commits, which were tested on Ubuntu 18.04

**Comment by lunarthegrey** [comment]
Thanks @Appleman1234, that fixed it.
