### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by gegtor** [lainchan/lainchan#158]
After fresh install Configuration tab shows

`
count(): Parameter must be an array or an object that implements Countable in /var/www/*redacted*/templates/cache/7b/7ba027ab1357be7ea484656db58c90b0c992d0d233fd112ee745a60523e20572.php at line 95
`
And nothing bellow loads

Ubuntu 18.04
Latest MySQL
Latest commits at the time of posting

**Comment by Appleman1234** [comment]
That should fix the issue. You will need to rebuild your templates using the Rebuild option.

**Comment by gegtor** [comment]
That fixed the issue

Thanks
