### ISSUE TITLE
Add better google analytics 

### ISSUE THREAD

**Issue by gegtor** [lainchan/lainchan#162]
I haven't checked but from what I remember vichan's google analytics was broken and badly implemented

Please rework google analytics 

And add a tracker script that would be inserted  in the <head> of each board
That way even when using one-page catalogue theme each board stats could be tracked

**Comment by gegtor** [comment]
I can confirm that with 
```
$config['google_analytics'] = 'UA-xxxxx-1';
$config['google_analytics_domain'] = 'xxxxx.org';
```

Tracking is not working

**Comment by Appleman1234** [comment]
Please provide additional information, other than it doesn't work. As for reworking it , that can be done, but it isn't a priority because lainchan doesn't use any analytics and when we did we used matamo / piwik instead of Google Analytics.

**Comment by gegtor** [comment]
I think that google urls changed since this was implemented by vichan

It basically returns 404 on doubleclick net site and google analytics shows zero trafic

**Comment by gegtor** [comment]
Where i can put my tracking script regardless if it's google analytics or something else?

It should appear in <head> on all pages

And it should survive rebuild

**Comment by gegtor** [comment]
Okay my fault 
Default tracking works but i had zero success with testing it because of my browser privacy settings both on Mac and IOS

**Comment by Appleman1234** [comment]
So is this fixed ? or did you still need Google Analytics stuff reworked ?

**Comment by gegtor** [comment]
It seems working so no

Before you close this issue
How can i add custom code to `<head>`?

I want to add apple touch icon

**Comment by Appleman1234** [comment]
Edit templates/header.html and add the code there. It already has an example for regular favicon of 
`    {% if config.url_favicon %}<link rel="shortcut icon" href="{{ config.url_favicon }}">{% endif %}`

**Comment by Appleman1234** [comment]
Alternatively, I just added config.appletouch_favicon support, so you can just set that, after pulling latest commit.
