### ISSUE TITLE
Spoiler / Delete images are broken

### ISSUE THREAD

**Issue by gegtor** [lainchan/lainchan#163]
Spoiler image links are broken in their default state
```
$config['spoiler_image'] = '/static/spoiler.png';
$config['image_deleted'] = '/static/deleted.png';
```
Leads to `//static/spoiler.png` which resoults in 404 error

So correct way is
```
$config['spoiler_image'] = 'static/spoiler.png';
$config['image_deleted'] = 'static/deleted.png';
```

Also even when this is set `deleted.png` is still broken because for some reason it's referenced to a current board not root
`https://xxx.org/b/static/deleted.png`
It should be
`https://xxx.org/static/deleted.png`

**Comment by Appleman1234** [comment]
That default was made with regards to certain expectations regarding your webhost configuration , which may not be true and may require you to change them in instance-config.php are you just proposing the default values be changed ?.

I can't reproduce the issue you mention with deleted.bng not being present, as it works in testing here.

**Comment by gegtor** [comment]
If it's URL rewriting thing then leave it as it is
