### ISSUE TITLE
Video expanding doesn't work

### ISSUE THREAD

**Issue by gegtor** [lainchan/lainchan#164]
For some reason video javascript doesn't load and when clicked it opens it in new tab
<img width="378" alt="Screenshot 2019-08-10 at 19 35 22" src="https://user-images.githubusercontent.com/10978723/62825262-47cd1300-bba9-11e9-8bf7-0063f2e3f526.png">

**Comment by gegtor** [comment]
Webm bar shows in Catalog but not on boards and is replaced by those two links

<img width="215" alt="Screenshot 2019-08-10 at 23 49 08" src="https://user-images.githubusercontent.com/10978723/62827124-84a90200-bbc9-11e9-84ad-5fb89fc31d64.png">
<img width="168" alt="Screenshot 2019-08-10 at 23 49 24" src="https://user-images.githubusercontent.com/10978723/62827125-84a90200-bbc9-11e9-8465-5870ebff2a84.png">

**Comment by Appleman1234** [comment]
I am still debugging this issue when you don't have `$config['additional_javascript'][] = 'js/options.js'
` enabled but the quick fix is to enable it, and then the error message you are seeing never gets called.

**Comment by gegtor** [comment]
With this added videos expand as expected
