### ISSUE TITLE
Banners don't work

### ISSUE THREAD

**Issue by gegtor** [lainchan/lainchan#165]
Banner script seems broken
<img width="274" alt="Screenshot 2019-08-10 at 21 01 53" src="https://user-images.githubusercontent.com/10978723/62825837-3a685680-bbb2-11e9-9f77-0b2bb2dcfd96.png">

But it works just fine in browser window `domain.org/banners.php`
<img width="1042" alt="Screenshot 2019-08-10 at 21 02 19" src="https://user-images.githubusercontent.com/10978723/62825836-3a685680-bbb2-11e9-9520-505332ff799c.png">

**Comment by Appleman1234** [comment]
Sorry, I am going to need more information, as the banner script works fine in testing here. Did you add 
` $config['url_banner'] = '/b.php';` to instance-config.php ? banners.php is separate to b.php and doesn't depend on any configuration setting.

**Comment by gegtor** [comment]
I was confused by how similar default banner.php was to banners.php

It works now with b.php
