### ISSUE TITLE
Where are ip notes displayed

### ISSUE THREAD

**Issue by gegtor** [lainchan/lainchan#168]
<img width="1279" alt="Screenshot 2019-08-17 at 23 24 18" src="https://user-images.githubusercontent.com/10978723/63217402-5afe5680-c146-11e9-81ec-edfc69307a97.png">
User has one IP note but it's nowhere to be found

**Comment by Appleman1234** [comment]
This should be fixed with the commit, above. Silly typographical errors.

**Comment by gegtor** [comment]
It's working now without a problem

Thanks
