### ISSUE TITLE
$config['filters'] maybe shouldn't discard posts with no body from different IP address

### ISSUE THREAD

**Issue by Wired-7** [lainchan/lainchan#169]
The filter 
```
// Minimum time between posts with the same text. (Same content, but not always the same IP address.)
	$config['filters'][] = array(
		'condition' => array(
			'flood-match' => array('body'), // Match only post body
			'flood-time' => &$config['flood_time_same']
		),
		'action' => 'reject',
		'message' => &$config['error']['flood']
	);
```
Discards posts from same and different IP addresses, even if they don't contain text. This even causes same IP address to be filtered when the post has no text. 
I feel it's not intended because there is another filter with an empty body exception:
```
// Minimum time between posts by the same IP address with the same text.
	$config['filters'][] = array(
		'condition' => array(
			'flood-match' => array('ip', 'body'), // Match IP address and post body
			'flood-time' => &$config['flood_time_ip'],
			'!body' => '/^$/', // Post body is NOT empty
		),
		'action' => 'reject',
		'message' => &$config['error']['flood']
	);
```
This results on posts from the same user having the config['flood_time_same'] .
Maybe the condition of no empty body should be added to the first filter.

**Comment by Appleman1234** [comment]
It looks intended to me, based on the git blame and previous commit message. The filters in config.php are supposed to be overridden based on user preference in instance-config.php anyways.
