### ISSUE TITLE
Please merge the 'anti bump flood' from Vichan

### ISSUE THREAD

**Issue by hawkoon** [lainchan/lainchan#173]
It was added to Vichan 15 days ago, commit: [1613f6b](https://github.com/vichan-devel/vichan/commit/1613f6baeab1a61ced5678bf2e6742cef36df4d9)
Basically it prevents shadow bumping (bumping a thread, then quickly deleting your reply so the thread stays at the top).

**Comment by Appleman1234** [comment]
Merged.
