### ISSUE TITLE
Various errors when trying to install

### ISSUE THREAD

**Issue by w3bb** [lainchan/lainchan#180]
I can't seem to install Lainchan. I wanted to mess around with configuration using the built in webserver (php -S) and I get these errors when accessing install.php
![](https://webber.rocks/21551cce11d433.png)

``PHP 7.4.6 (cli) (built: May 22 2020 22:44:37) ( NTS )
``

**Comment by rmrhz** [comment]
Not a related error to lainchain but to [twigphp/Twig](https://github.com/twigphp/Twig)

**Comment by w3bb** [comment]
@rmrhz The deprecation errors at least

**Comment by w3bb** [comment]
It seems downgrading to 7.3 fixed all the issues

**Comment by rmrhz** [comment]
@w3bb Kindly close this issue.

**Comment by w3bb** [comment]
@rmrhz Is it not working with 7.4(.6) a non issue? It might be worth it for me to rename this issue to something more descriptive to address it if it is.

**Comment by rmrhz** [comment]
I could agree to you in a certain degree but you can submit a pull request indicating a maximum version number of PHP that would avoid the deprecation errors. Since in the README there isn't a minimum version nor a maximum version of PHP indicated as a requirement.

**Comment by w3bb** [comment]
I see what you mean. I figured it meant 7.x, dumb me. Closing.
