### ISSUE TITLE
Issues with posting webm

### ISSUE THREAD

**Issue by ShiroBlank** [lainchan/lainchan#185]
When a user tries to post a webm an error shows up saying "Invalid image."

I'm running php7.3 and I've configured php.ini to have a max upload of 40M.
I'm also running ffmpeg version 4.1.6-1~deb10u1.
I'm running GraphicMagik not ImageMagik.
I've setup my instance-config.php with the following:

$config['allowed_ext'][] = 'webm';
$config['webm']['use_ffmpeg'] = true;
$config['additional_javascript'][] = 'js/options.js';
$config['additional_javascript'][] = 'js/webm-settings.js';
$config['additional_javascript'][] = 'js/expand-video.js';
$config['allowed_ext'][] = 'mp4';

I'm pretty lost right now. Any help appreciated!

**Comment by rmrhz** [comment]
I'll try to reproduce the error over the weekend.

**Comment by rmrhz** [comment]
@ShiroBlank I've managed to reproduce the error. This iteration of vichan doesn't handle mp4 files.

**Comment by ShiroBlank** [comment]
> @ShiroBlank I've managed to reproduce the error. This iteration of vichan doesn't handle mp4 files.

Thanks for checking it out! is there any patches I could apply to get them working? Or is it just not possible.

**Comment by Appleman1234** [comment]
@rmrhz you are mistaken, the reason mp4 files are not working, is because they only work if FFMpeg is installed and used for thumbnailing. Is ffmpeg in path, or are the following config options set

`$config['allowed_ext_files'][] = 'mp4';`

`$config['webm']['ffmpeg_path'] = '/path/to/ffmeg';
$config['webm']['ffprobe_path'] = '/path/to/ffprobe';`

**Comment by rmrhz** [comment]
@Appleman1234 Thanks for clarifying that out. What failed in my test is the thumb method in which I don't have `$config['thumb_method'] = 'gm'`.

**Comment by ShiroBlank** [comment]
@Appleman1234 Thanks for replying! I've got both of those set within my config file and I installed ffmpeg via package manager so it's already in path(?) ((It's installed under /bin and /bin is set in $path already)).
