### ISSUE TITLE
OP's postId is greater than next post's postId

### ISSUE THREAD

**Issue by K1rakishou** [lainchan/lainchan#189]
https://lainchan.org/%CE%A9/res/36474.html

OP postId - https://lainchan.org/%CE%A9/res/36474.html#36474
Next post postId - https://lainchan.org/%CE%A9/res/36474.html#36456

I dunno how this happened but it breaks post sorting and can lead to other nasty bugs on third-party clients.

**Comment by Appleman1234** [comment]
This is due to merge thread functionality, and it doesn't break anything.

**Comment by K1rakishou** [comment]
>and it doesn't break anything

Whoops, my bad, I meant it breaks third-party clients, not the site.

>This is due to merge thread functionality

Well if it's not a bug and is supposed to work like this then I guess this issue can be closed.
