### ISSUE TITLE
Database error: SQLSTATE[HY000] [1045] Access denied for user 'hidden'@'localhost' (using password: YES) in mod.php 

### ISSUE THREAD

**Issue by dimension7front** [lainchan/lainchan#194]
I get the above error when trying to login to mod.php after I finished installing lainchan. 
Yes, I am using the default admin/password combination, this is what it gives now. 
Any ideas?

**Comment by Appleman1234** [comment]
There is no default mysql username and password combination. 
E.g. ```
	$config['db']['user'] = '';
	$config['db']['password'] = '';
	$config['db']['database'] = '';
```
in the default config.php,
	
	You need to set those values ideally in instance-config.php, and have a valid mysql user and database created.
