### ISSUE TITLE
Feature request: Support for Securimage PHP Captcha

### ISSUE THREAD

**Issue by maq33** [lainchan/lainchan#195]
https://www.phpcaptcha.org/

https://www.phpcaptcha.org/try-securimage/

I want to host a chan on Tor (.onion site) and I need a captcha that works without need of JavaScript for preventing spam and flood.

This is a vary good idea, users worried about information leaking in browser because of JavaScript, can benefit with this.

Please, implement this.

**Comment by Appleman1234** [comment]
This was implemented in https://github.com/lainchan/lainchan/commit/53ffe8f49ce7ba21ea22c373e0d8a659ab582e78
