### ISSUE TITLE
lainfag software not working

### ISSUE THREAD

**Issue by rfc-2549** [lainchan/lainchan#209]
Not only if shits itself if running a compressible version of PHP, but also when you try to post it gives a error with 0 elaboration.

Appleman1234, please get your shit together before writing software.

**Comment by Appleman1234** [comment]
Sorry but without more information, I am not able to help you.

**Comment by rfc-2549** [comment]
I solved my issue by using an imageboard that was not written by lainfags.

**Comment by Appleman1234** [comment]
Sorry but without more information, I am not able to help you.

**Comment by lelenium** [comment]
based

so fucking zased
i kneel sir qorg
