### ISSUE TITLE
The server took too long to submit your post. Your post was probably still submitted. If it wasn't, we might be experiencing issues right now -- please try your post again later.

### ISSUE THREAD

**Issue by TheLogan117** [lainchan/lainchan#212]
Been trying to redact my post a few times and uploading via Firefox and MS Edge, but the same error keeps popping up constantly. Tried to report this on /q/ (replying to an existing post) and same thing happens but without the following content:

`{"readyState":4,"responseText":"{\"error\":\"Caught fatal error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in \\/var\\/www\\/html\\/inc\\/filters.php:120\\nStack trace:\\n#0 \\/var\\/www\\/html\\/inc\\/filters.php(120): PDOStatement->execute()\\n#1 \\/var\\/www\\/html\\/inc\\/filters.php(210): Filter->match()\\n#2 \\/var\\/www\\/html\\/inc\\/filters.php(272): Filter->check()\\n#3 \\/var\\/www\\/html\\/post.php(911): do_filters()\\n#4 \\/var\\/www\\/html\\/post.php(1439): handle_post()\\n#5 {main}\\n  thrown in \\/var\\/www\\/html\\/inc\\/filters.php at line 120\"}","responseJSON":{"error":"Caught fatal error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in /var/www/html/inc/filters.php:120\nStack trace:\n#0 /var/www/html/inc/filters.php(120): PDOStatement->execute()\n#1 /var/www/html/inc/filters.php(210): Filter->match()\n#2 /var/www/html/inc/filters.php(272): Filter->check()\n#3 /var/www/html/post.php(911): do_filters()\n#4 /var/www/html/post.php(1439): handle_post()\n#5 {main}\n  thrown in /var/www/html/inc/filters.php at line 120"},"status":500,"statusText":"error"}`

Was it worth submitting a report? Or was it not, and I should wait a few hours before posting?

![trying to upload a new post](https://github.com/lainchan/lainchan/assets/39456791/dfd5e41f-dc88-4579-b7f0-7bcb557a793a)
![uploading a reply to existing post](https://github.com/lainchan/lainchan/assets/39456791/dfff06b2-af30-4858-a9f9-ba49b74809eb)

**Comment by Appleman1234** [comment]
This should be resolved. It was an issue with a new feature I was testing and will merge to Github later.
