### ISSUE TITLE
making multiple posts 

### ISSUE THREAD

**Issue by kaly-x** [lainchan/lainchan#28]
When you submit a new post, you cannot make another one until you refresh. The "post" button stays "posted".
<img width="412" alt="screen shot 2015-09-04 at 1 41 03 pm" src="https://cloud.githubusercontent.com/assets/10324440/9691829/a0c96e9c-530a-11e5-8a8d-c4285829f7b5.png">

**Comment by tjohnman** [comment]
I spend all day working with this kind of stuff and I'm really tired. I'll try to contribute next weekend.
Buf for anyone that fancies looking into this in the meantime:

Looking at this error on posting a new message:
`Uncaught TypeError: Cannot read property 'top' of undefined` (ajax.js:97)

I can see that at the point where this is called:
`$(window).scrollTop($('div.post#reply_' + post_response.id).offset().top);`
the response DIV has not yet appeared. Autoreload is triggered, but we don't wait for it to take effect before trying to access the response DIV. Thus it's undefined.

If I'm not mistaken, the attempt to modify the window's scroll position should be made inside the AJAX success handler (three lines above the reported error).

This, of course, assuming this JavaScript error is causing the script that would reset the post button to interrupt.

**Comment by tjohnman** [comment]
Please note this particular issue is fixed as can be checked on /test/.
There is still a problem to be resolved, and that is proper automatic loading and highlighting of the new post (this should be trivial, but I'm finding it very hard to fix for some reason).

However reload is no longer necessary for further posting. The issue, as described by kaly-x, is no longer present.

**Comment by AshtonHarding** [comment]
We need to close this one, since it's no longer an issue.

**Comment by Appleman1234** [comment]
Closing as no longer an issue.
