### ISSUE TITLE
$config['board_locked'] = false;

### ISSUE THREAD

**Issue by kaly-x** [lainchan/lainchan#40]
When $config['board_locked'] = false; is set to true, people can still post in the locked board.  We have this set on /tech/ and /archive/ right now and it does not work.

**Comment by chudeki8** [comment]
Have you tried `$config['board_locked'] = ['tech', 'archive'];`?

**Comment by kaly-x** [comment]
Yes and it works
On Aug 11, 2016 1:32 PM, chudeki8 <notifications@github.com> wrote:Have you tried $config['board_locked'] = ['tech', 'archive'];?

**Comment by chudeki8** [comment]
Opps, didn't know I was necro fixing this :p
