### ISSUE TITLE
automated post discarded

### ISSUE THREAD

**Issue by chudeki8** [lainchan/lainchan#5]
Hi, I saw some talk on [/q/](https://lainchan.org/q/res/2931.html) about the board accidentally blocking some posts with a message "Your request looks automated; Post discarded." 

I couldn't reproduce it (tried firefox, chromium, android browser, and safari 5). It looks like there was a [similar issue in tinyboard](https://github.com/savetheinternet/Tinyboard/issues/142) though.  Not sure if it's related.

**Comment by tjohnman** [comment]
Unfortunately, it looks like they couldn't confirm if their solution had a fix. Unless there's a way to properly reproduce this, it's going to be very difficult to fix if at all.

**Comment by rajlaksh** [comment]
I am facing this issue currently and nothing is working at all. I tried different browsers,different browsers versions, tried useragents switcher,tried proxies,tried vpn and still I can't create any thread at all.
Also those javascript options at right-top aren't working.

**Comment by rmrhz** [comment]
What kind of content are posting? What are the sent HTTP headers? Any more information you can provide @rajlaksh?

**Comment by rajlaksh** [comment]
I' just posting normal content with recpatcha v2.

That error show only when using No Recaptcha.
