### ISSUE TITLE
Thumbnails for PDFs / other things

### ISSUE THREAD

**Issue by barrucadu** [lainchan/lainchan#6]
At the very least, there should be a fixed image, but generating the image from the file itself would be nice, and imagemagick can do that for PDFs at least.

**Comment by AshtonHarding** [comment]
I recommend changing the variables, and testing it first. But this should theoretically work. (I didn't know where to put this .__.)

https://raw.githubusercontent.com/AshtonHarding/some_php_scripts/master/pdf_to_thumbnail.php

**Comment by AshtonHarding** [comment]
https://ghostbin.com/paste/72o3o I have this written, I just don't know
1.) Where to put it
2.) How to hook it up to each uploaded pdf

**Comment by thingscouldbeworse** [comment]
This looks easy enough, but it's not possible without imagick (or at least ghostscript commands). Does lainchan use imagick for image thumbnails now? Or does it at least have it available for use?

**Comment by Appleman1234** [comment]
Implemented ticket as specified, closing. Feel free to reopen or make a new ticket with new requirements as necessary.
