### ISSUE TITLE
Delete/report forms are duplicated

### ISSUE THREAD

**Issue by Leodmanx2** [lainchan/lainchan#80]
When the checkbox next to a user's name is ticked two forms offering options for the user to report or delete the post appear. Supposedly, the forms are identical and there should only be one. The issue applies to all styles and browsers.

![A screenshot of the duplicated form](https://0x0.st/jcC.png)

As an aside, the match between checkbox and per-post form is a bit confusing. Am I reporting all the checked posts when I submit one of the forms or only the post it appears alongside? A bit of sense would say the latter and the page source indicates the same, but that I had to check the page source to be sure should say something. I would suggest changing the button to something else.

**Edit:** I also notice the form doesn't appear at all unless you're on the thread's page. The checkboxes are, of course, present despite doing nothing.

**Comment by Appleman1234** [comment]
This has been fixed  by merging pull request #79.
