### ISSUE TITLE
Add image-orientation: from-image

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [lainchan/lainchan#83]
My web browser [does not have automatic EXIF rotation of images](https://forum.palemoon.org/viewtopic.php?p=84579), and there is no way to add custom CSS to Lainchan currently.

Would it be too much trouble to add something along the lines of

````
img {
   image-orientation: from-image;
}
````

to the universal CSS of the board?

**Comment by Appleman1234** [comment]
I had added to this to the site's stylesheets/style.css, but haven't committed it to Github yet because 
http://caniuse.com/#feat=css-image-orientation the functionality that you are requesting is browser specific and is only supported in Firefox at this time.

**Comment by spedru** [comment]
A cursory search of the repo shows that browser-specific stylesheet lines are nothing new to it. With your permission I'll just add it in.

**Comment by Appleman1234** [comment]
Added in commit 9716372fcaa833ebca02d5b3530e956ba0938400 , closing this issue as implemented.
