### ISSUE TITLE
Deleting all posts by IP (D++) doesn't seem to work properly

### ISSUE THREAD

**Issue by barrucadu** [lainchan/lainchan#87]
A user posted a thread on /r/ saying "now its time to post some cp lets go everyone", and replied twice. As there were multiple posts, I didn't just `B&D`, I hit `D++` (even though, as I realised a moment later, just deleting the OP was sufficient).

I confirmed the delete all, it shows up in the mod log, but the thread remained until I just hit `D` on the OP. Posts on boards other than /r/ (one each on /q/ and /civ/) did get deleted, however.

Is there perhaps a problem with `D++` on threads?

(in retrospect, `D++` was an overreaction as it did do collateral damage to other boards, but it's hard not to have a knee-jerk reaction in this situation)

**Comment by Appleman1234** [comment]
This is because of a race condition with the autotagging of IP notes on deletion, I will look into it again.

**Comment by Appleman1234** [comment]
This should be working again , but I haven't closed it because the header redirect generates the following warning "PHP message: PHP Warning:  Cannot modify header information - headers already sent by ... and displays a blank page.

**Comment by barrucadu** [comment]
Is there perhaps a space before a `<?php` somewhere?
