### ISSUE TITLE
Edit post form does not escape HTML entities.

### ISSUE THREAD

**Issue by barrucadu** [lainchan/lainchan#94]
1. I made a post on /mod/ with the title `Draft News Post: "The lainchan.jp Incident"`
2. I edited it, and the Chromium-rendered title box only contained the string `Draft News Post: `
3. This is the actual HTML produced, the cause looks pretty obvious:

```html
<input style="float:left;" type="text" name="subject" size="25" maxlength="100" autocomplete="off" value="Draft News Post: "The lainchan.jp Incident"">
```

**Comment by Appleman1234** [comment]
Fixed, verified on site, and closed.
