### ISSUE TITLE
OS Version of lainchan's server

### ISSUE THREAD

**Issue by KuroAku** [lainchan/lainchan#97]
I'm building a Vagrant box to aid development and OS should be as close as posible

**Comment by Appleman1234** [comment]
Before the wipe the OS was Ubuntu Xenial, see an existing Vagrant file at https://github.com/sometoby/lainchan/commit/2ca377ee59c6eacd433910ab6c670c16c563a83c , after the wipe, the OS is Debian jessie. 

To be honest, the OS of vagrant files doesn't matter that much, and I don't mind if people write Vagrant files or other automation (Docker, Ansible,Salt,etc) for whatever OS they want to use. As far as I know we support both nginx or Apache or insert other webserver here, PHP 5 or PHP 7, MariaDB or MySQL and a variety of other choices.
