### ISSUE TITLE
Invalid link_for call referencing deleted thread when op is deleted

### ISSUE THREAD

**Issue by horija** [lainchan/lainchan#98]
I'm getting this error on vichan when deleting OP'S thread from the front end when using the password deletion. It came from the slugify modification particularly the link_for change  at line 245 in post.php:
Undefined index: id in C:\wamp64\www\hokachan\inc\functions.php 

`'/' . $board['dir'] . $config['dir']['res'] . link_for($post) . ($post['thread'] ? '#' . $id : '')`

Changing it to the pre slugify code fixes it though. 

`'/' . $board['dir'] . $config['dir']['res'] . sprintf($config['file_page'], $post['thread'] ? $post['thread'] : $id) . ($post['thread'] ? '#' . $id : '')`

**Comment by Appleman1234** [comment]
Yes , I could replicate this error message using lainchan and have fixed it using the method you suggested.
